apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  db-user: {{ .Values.postgresql.postgresUser | b64enc }}
  db-password: {{ .Values.postgresql.postgresPassword | b64enc }}
  secret-key: {{ .Values.secrets.secretKey | b64enc }}
